[global]
    quiet = false
    show_hash = false
    upgrade_only = true
    system = "linux/amd64"
    asset_filters = [ "x86_64", "^musl", "AppImage"]

["ogham/exa"]
    asset_filters = ["^musl"]

["sxyazi/yazi"]
    asset_filters = ["x86_64-unknown-linux-gnu.zip"]

["lasantosr/intelli-shell"]
    asset_filters = ["x86_64-unknown-linux-gnu"]

["atuinsh/atuin"]
    asset_filters = ["x86_64-unknown-linux-gnu.tar.gz"]

["sharkdp/vivid"]
    asset_filters = ["x86_64-unknown-linux-gnu.tar.gz"]

["MordechaiHadad/bob"]
    asset_filters = ["bob-linux-x86_64.zip"]

["janhq/jan"]
    asset_filters = ["AppImage"]

["astral-sh/uv"]
    asset_filters = ["uv-x86_64-unknown-linux-musl.tar.gz"]
    all = true

["astral-sh/ruff"]
    asset_filters = ["ruff-x86_64-unknown-linux-musl.tar.gz"]

["zed-industries/zed"]
    asset_filters=["zed-linux-x86_64.tar.gz"]

["ollama/ollama"]
    asset_filters=["ollama-linux-amd64.tgz"]

["jtroo/kanata"]
    asset_filters=["kanata_cmd_allowed"]

['Wilfred/difftastic']
    asset_filters = ["difft-x86_64-unknown-linux-musl"]
