export DISABLE_CORRECTION="true"

function load_antigen() {
  ANTIGEN_HOME="$HOME/.antigen-repo"
  ANTIGEN_REPO="https://github.com/zsh-users/antigen.git"
  ANTIGEN_FILE="$ANTIGEN_HOME/antigen.zsh" 
  if [ ! -f $ANTIGEN_FILE ]; then
    echo "antigen not found"
    git clone $ANTIGEN_REPO $ANTIGEN_HOME
  fi
  source $ANTIGEN_FILE
}

bind_keys() {
  # Vi-mode
  # antigen bundle vi-mode # Only for prompt
  # antigen bundle sharat87/zsh-vim-mode
  bindkey "^R" history-incremental-search-backward
  bindkey "^F" forward-char # Make them work in vicmd
  bindkey "^D" delete-char-or-list
}

function apply_bundles() {
  if (type antigen | grep -e 'function' > /dev/null); then
    # antigen bundle sharat87/autoenv
    antigen bundle zsh-users/zsh-syntax-highlighting 
    antigen bundle tarruda/zsh-autosuggestions

    antigen bundle gmatheu/shell-plugins explain-shell
    antigen bundle gmatheu/shell-plugins dirrc
    antigen bundle gmatheu/shell-plugins docker
    antigen bundle gmatheu/shell-plugins notify
    antigen bundle gmatheu/shell-plugins git
    antigen bundle gmatheu/shell-plugins git-svn 
    antigen bundle gmatheu/shell-plugins vim
    antigen bundle gmatheu/shell-plugins svn
    antigen bundle gmatheu/shell-plugins virtualbox
    antigen bundle gmatheu/shell-plugins xclip 
    antigen bundle gmatheu/shell-plugins grep
    antigen bundle gmatheu/shell-plugins fast-server
    antigen bundle gmatheu/shell-plugins start-me-up
    antigen bundle gmatheu/shell-plugins java
    antigen bundle gmatheu/shell-plugins tmux
    antigen bundle gmatheu/dotfiles shell-plugin

    antigen use oh-my-zsh
    antigen bundle docker 
    antigen bundle gradle 
    antigen bundle lein 
    antigen bundle bundler 
    antigen bundle git 
    antigen bundle git-extras 
    antigen bundle rake 
    antigen bundle autojump 
    antigen bundle rvm 
    antigen bundle vagrant 
    antigen bundle rails 
    antigen bundle history 
    antigen bundle debian 
    antigen bundle history-substring-search 
    antigen bundle command-not-found 
    antigen bundle svn-fast-info

    antigen theme robbyrussell 

    antigen apply
  fi
}

function extra_init(){
  d=~/.dircolors
  test -r $d && eval "$(dircolors $d)"
  export GREP_COLOR='1;31'
}

function aliases() {
  alias zsh_reload='source ~/.zshrc'
  alias zshr='zsh_reload'
  alias o="xdg-open"
  alias xml='xmllint --format -'
}

load_antigen
bind_keys
apply_bundles
extra_init
aliases

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

if [ -f ~/.profile ]; then
  source ~/.profile
fi

